
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_app
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: meu_banco
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha123
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - appnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - appnet
  app:
    build: ..
    container_name: node_app
    restart: always
    volumes:
      - ../src/:/app
      - /app/node_modules
    environment:
      DB_HOST: mysql_app
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: alunos
      DB_PORT: 3306
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      - appnet

# Definição da rede customizada
networks:
  appnet:
    driver: bridge